<Project>
  <PropertyGroup>
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
    <NoWarn>$(NoWarn);STX0001;STX0002;STX0004;STX0005;STX0006;STX0007;STX0008;STX0009;STX0010;STX0011;STX0012;STX0014;STX0015;STX0018;STX0019;STX0023;STXAPI001;STXAPI002;STXAPI004;STXAPP005;STXB002;STXB003;STXB005;STXD001;STXE002;STXEX001;STXEX002;STXEX003;STXF002;STXFORMAT001;STXFORMAT002;STXFORMAT003;STXFORMAT004;STXFORMAT005;STXFORMAT007;STXFORMAT008;STXFORMAT009;STXFORMAT011;STXFORMAT012;STXM002;STXO001;STXSTRUCT001;STXTEST001;STXTEST004;STXTEST005</NoWarn>
  </PropertyGroup>
</Project>
